<x-qr-code.type :types="[
    [
        'id' => 1,
        'value' => 'website',
        'title' => 'Website',
        'text' => 'Link to an existing web URL and bring traffic online',
        'image' => 'https://dashboard.uniqode.com/assets/img/dynamic-qr/website.svg',
    ],
    [
        'id' => 2,
        'value' => 'pdf',
        'title' => 'Pdf',
        'text' => 'Link a PDF document and distribute it efficiently',
        'image' => 'https://dashboard.uniqode.com/assets/img/dynamic-qr/pdf.svg',
    ],
    [
        'id' => 3,
        'value' => 'image',
        'title' => 'Image',
        'text' => 'Show A Photo',
        'image' => 'https://dashboard.uniqode.com/assets/img/dynamic-qr/image.svg',
    ],
    [
        'id' => 4,
        'value' => 'sms',
        'title' => 'Sms',
        'text' => 'Redirect to your mobile number to receive SMS',
        'image' => 'https://dashboard.uniqode.com/assets/img/dynamic-qr/sms.svg',
    ],
    [
        'id' => 5,
        'value' => 'email',
        'title' => 'Email',
        'text' => 'Link to receive email messages',
        'image' => 'https://dashboard.uniqode.com/assets/img/dynamic-qr/email.svg',
    ],
    [
        'id' => 6,
        'value' => 'mobile_app',
        'title' => 'Mobile App',
        'text' => 'Link to receive email messages',
        'image' => 'https://dashboard.uniqode.com/assets/img/dynamic-qr/app-download.svg',
    ],
    [
        'id' => 7,
        'value' => 'call',
        'title' => 'Call',
        'text' => 'Link to receive email messages',
        'image' => 'https://dashboard.uniqode.com/assets/img/dynamic-qr/call.svg',
    ],
    [
        'id' => 8,
        'value' => 'location',
        'title' => 'Location',
        'text' => 'Point to any location on Google Maps',
        'image' => 'https://dashboard.uniqode.com/assets/img/dynamic-qr/location.svg',
    ],
    [
        'id' => 9,
        'value' => 'coupon_code',
        'title' => 'Coupon Code',
        'text' => 'Route to a page displaying coupon code details',
        'image' => 'https://dashboard.uniqode.com/assets/img/dynamic-qr/coupon.svg',
    ],
    [
        'id' => 10,
        'value' => 'social',
        'title' => 'Social',
        'text' => 'Link to an existing web URL and bring traffic online',
        'image' => 'https://dashboard.uniqode.com/assets/img/dynamic-qr/social-media.svg',
    ],
    [
        'id' => 11,
        'value' => 'audio',
        'title' => 'Audio',
        'text' => 'Link to your phone number for quick calls',
        'image' => 'https://dashboard.uniqode.com/assets/img/dynamic-qr/business-page.svg',
    ],
    [
        'id' => 12,
        'value' => 'business_page',
        'title' => 'Business Page',
        'text' => 'Link to your phone number for quick calls',
        'image' => 'https://dashboard.uniqode.com/assets/img/dynamic-qr/mp3.svg',
    ],
    [
        'id' => 13,
        'value' => 'restaurant',
        'title' => 'Restaurant Menu',
        'text' => 'Link to your restaurant and upload menu',
        'image' => 'https://i.ibb.co/kx55Xpv/Restaurant-Icon.png',
    ],
    [
        'id' => 14,
        'value' => 'facebook_page',
        'title' => 'Facebook Page',
        'text' => 'Link to your facebook page.',
        'image' => 'https://dashboard.uniqode.com/assets/img/dynamic-qr/facebook.svg',
    ],
]" />
