<x-qr-code.type :types="[
    [
        'id' => 1,
        'value' => 'website',
        'title' => 'Website',
        'text' => 'Link to an existing web URL and bring traffic online',
        'image' => asset('images/d-image/website.svg'),
    ],
    [
        'id' => 2,
        'value' => 'pdf',
        'title' => 'Pdf',
        'text' => 'Link a PDF document and distribute it efficiently',
        'image' => asset('images/d-image/pdf.svg'),
    ],
    [
        'id' => 3,
        'value' => 'image',
        'title' => 'Image',
        'text' => 'Show A Photo',
        'image' => asset('images/d-image/images.svg'),
    ],
    [
        'id' => 4,
        'value' => 'sms',
        'title' => 'Sms',
        'text' => 'Redirect to your mobile number to receive SMS',
        'image' => asset('images/d-image/sms.svg'),
    ],
    [
        'id' => 5,
        'value' => 'email',
        'title' => 'Email',
        'text' => 'Link to receive email messages',
        'image' => asset('images/d-image/email.svg'),
    ],
    [
        'id' => 6,
        'value' => 'mobile_app',
        'title' => 'Mobile App',
        'text' => 'Link to receive email messages',
        'image' => asset('images/d-image/app-downloader.svg'),
    ],
    [
        'id' => 7,
        'value' => 'call',
        'title' => 'Call',
        'text' => 'Link to receive email messages',
        'image' => asset('images/d-image/call.svg'),
    ],
    [
        'id' => 8,
        'value' => 'location',
        'title' => 'Location',
        'text' => 'Point to any location on Google Maps',
        'image' => asset('images/d-image/location.svg'),
    ],
    [
        'id' => 9,
        'value' => 'coupon_code',
        'title' => 'Coupon Code',
        'text' => 'Route to a page displaying coupon code details',
        'image' => asset('images/d-image/coupon.svg'),
    ],
    [
        'id' => 10,
        'value' => 'social',
        'title' => 'Social',
        'text' => 'Link to an existing web URL and bring traffic online',
        'image' => asset('images/d-image/social-media-qr-icons.svg'),
    ],
    [
        'id' => 11,
        'value' => 'audio',
        'title' => 'Audio',
        'text' => 'Link to your phone number for quick calls',
        'image' => asset('images/d-image/mp3-qr-icons.svg'),
    ],
    [
        'id' => 12,
        'value' => 'business_page',
        'title' => 'Business Page',
        'text' => 'Share your Business',
        'image' => asset('images/d-image/business-page-qr-icons.svg'),
    ],
    [
        'id' => 13,
        'value' => 'restaurant',
        'title' => 'Restaurant',
        'text' => 'Link to your restaurant and upload menu',
        'image' => asset('images/d-image/resturent-qr-icons.png'),
    ],
    [
        'id' => 14,
        'value' => 'facebook_page',
        'title' => 'Facebook Page',
        'text' => 'Link to your facebook page.',
        'image' => asset('images/d-image/facebook-qr-icons.svg'),
    ],
]" />
